// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nekqnvcbqlinvhhsvnrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la3FudmNicWxpbnZoaHN2bnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTM1MjAsImV4cCI6MjA2NTY2OTUyMH0.cL_YB4MM0l84DpN7zbwnnPHQsjFU87rnEpX0JYADAM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);